meta:
  audio_features: '/media/zunaron/Daten/Uni - Augsburg/9. Semester/Projektarbeit/CUB-200 Scripts/Embeddings/Audio/combined_data.csv'
  image_features: '/media/zunaron/Daten/Uni - Augsburg/9. Semester/Projektarbeit/CUB-200 Scripts/Embeddings/Image/combined_data.csv'
  text_features: ???  # path to CSV with text features
  numeric_features: '/media/zunaron/Daten/Uni - Augsburg/9. Semester/Projektarbeit/CUB-200 Scripts/Embeddings/Numerical/avonet.csv'
  meta_type: 'numeric'
  results_root: '/media/zunaron/Daten/Uni - Augsburg/9. Semester/Projektarbeit/Results_avonet_combined'  # path to store results in
  device: cuda:0
  split: random
  model: linear
  embeddings_are_2D: False
  use_predefined_clf_sets: False
  predefined_clf_split: ??? # path to the folder containing the predefined zsl classification split (train, devel, test csvs), e.g. "./splits/bird_classification"
  predefined_zsl_splits: ??? # path to the folder containing the five splits with each having (train, devel, test csvs), e.g. "./splits/zsl-5fold"
  mapping_path: ??? # Path to the json file containing the mapping dictionary # e.g. ./embeddings/baseline_embeddings/mapping.json
hparams:
  batch_size: 16
  learning_rate: 0.0001
  optimizer: SGD
  epochs: 30
  seed: 23
  compatibility: dot_product
  loss: ranking
  normalisation_type: column